const records = [
    {
        id: "brandenburgische",
        title: "Brandenburgische Konzerte",
        artist: "Johann Sebastian Bach",
        year: "1971",
        theme: "light",
        sky: "images/brandenburgische_sky.jpg",
        temp: -4,
        tempPosition: 2,
        visibility: "Crystal Clear",
        pressure: "High, Stable",
        skyDesc: "Pale Winter White",
        desc: "Six concertos, each one a different configuration of instruments. The interplay feels inevitable, like the parts were always meant to find each other. Music that rewards close listening but doesn't demand it."
    },
    {
        id: "fresh-fruit",
        title: "Fresh Fruit for Rotting Vegetables",
        artist: "Dead Kennedys",
        year: "1980",
        theme: "light",
        sky: "images/fresh-fruit_sky.jpg",
        temp: 2,
        tempPosition: 5,
        visibility: "Poor",
        pressure: "Falling Fast",
        skyDesc: "Concrete, Angry Grey",
        desc: "Debut record, fully formed and furious. Jello Biafra writes lyrics like a satirist who's also genuinely angry. The guitar tone is sharp and uncomfortable in exactly the right way."
    },
    {
        id: "rat-music",
        title: "Rat Music for Rat People",
        artist: "Various",
        year: "1982",
        theme: "light",
        sky: "images/rat-music_sky.jpg",
        temp: 3,
        tempPosition: 8,
        visibility: "Very Low",
        pressure: "Low, Unstable",
        skyDesc: "Smudged, Industrial Dark",
        desc: "SF hardcore comp that captures a moment. Code of Honor, Flipper, MDC — the range of what punk could sound like in one city at one time. Essential document."
    },
    {
        id: "sex-bomb-baby",
        title: "Sex Bomb Baby",
        artist: "Flipper",
        year: "1988",
        theme: "light",
        sky: "images/sex-bomb-baby_sky.jpg",
        temp: 4,
        tempPosition: 10,
        visibility: "Very Low",
        pressure: "Low, Erratic",
        skyDesc: "Bruised, Oil-Slick Dark",
        desc: "Compilation of early singles and rarities. Slower and heavier than most punk, almost sludgy. Will Shatter's bass is the whole foundation. An acquired taste that sticks."
    },
    {
        id: "mark-of-the-mole",
        title: "Mark of the Mole",
        artist: "The Residents",
        year: "1981",
        theme: "light",
        sky: "images/mark-of-the-mole_sky.jpg",
        temp: 4,
        tempPosition: 12,
        visibility: "Near Zero",
        pressure: "Very Low, Collapsing",
        skyDesc: "Black, Starless Void",
        desc: "First part of a trilogy about migrating workers. The Residents at their most narrative and strange. Repetitive in a way that builds rather than bores. Uncommitted listeners need not apply."
    },
    {
        id: "madvillainy",
        title: "Madvillainy",
        artist: "Madvillain",
        year: "2004",
        theme: "light",
        sky: "images/madvillainy_sky.jpg",
        temp: 11,
        tempPosition: 15,
        visibility: "Very Low",
        pressure: "Low, Building",
        skyDesc: "Dead, Grey Noon",
        desc: "DOOM and Madlib operating at a level that still sounds untouched. Short tracks, dense with wordplay, buried samples, and an atmosphere that feels overcast even on a clear day. One of the records I keep coming back to."
    },
    {
        id: "morally-bankrupt",
        title: "Morally Bankrupt",
        artist: "Morally Bankrupt",
        year: "1986",
        theme: "light",
        sky: "images/morally-bankrupt_sky.jpg",
        temp: 7,
        tempPosition: 17,
        visibility: "Low",
        pressure: "Falling",
        skyDesc: "Flat, Featureless Grey",
        desc: "Regional hardcore that never got the attention it deserved. Tight, direct, and mean in the best sense. The kind of record that only exists because someone needed to make it."
    },
    {
        id: "holy-wars",
        title: "Holy Wars",
        artist: "Tuxedo Moon",
        year: "1985",
        theme: "light",
        sky: "images/holy-wars_sky.jpg",
        temp: 8,
        tempPosition: 20,
        visibility: "Low",
        pressure: "Low, Brooding",
        skyDesc: "Cold, Cathedral Blue",
        desc: "Post-punk with classical and electronic elements woven through it. Blaine Reininger's violin and the tape work give it a theatrical quality that doesn't feel overdone. Cold and considered."
    },
    {
        id: "telephone-free",
        title: "Telephone Free Landslide Victory",
        artist: "Camper Van Beethoven",
        year: "1985",
        theme: "light",
        sky: "images/telephone-free_sky.jpg",
        temp: 9,
        tempPosition: 23,
        visibility: "Moderate",
        pressure: "Unsettled",
        skyDesc: "Restless, Shifting Cloud",
        desc: "Debut that sounds like a band pulling from every direction at once and somehow holding it together. Ska, folk, psych, whatever. Take the Skinheads Bowling is still one of the great absurdist punk songs."
    },
    {
        id: "vs",
        title: "V.S.",
        artist: "Mission of Burma",
        year: "1982",
        theme: "light",
        sky: "images/vs_sky.jpg",
        temp: 9,
        tempPosition: 25,
        visibility: "Low",
        pressure: "Rising Sharp",
        skyDesc: "Harsh, Blinding White",
        desc: "Post-punk that hits harder than most. Roger Miller's guitar is dissonant and precise, Clint Conley's bass is the counterweight. Tapes from Martin Swope thread through everything. Still sounds like the future."
    },
    {
        id: "document",
        title: "Document",
        artist: "R.E.M.",
        year: "1987",
        theme: "light",
        sky: "images/document_sky.jpg",
        temp: 10,
        tempPosition: 28,
        visibility: "Moderate",
        pressure: "Steady, Uncertain",
        skyDesc: "Overcast, Restless",
        desc: "The record where R.E.M. got louder without losing the texture. It's the End of the World as the opener, then it actually gets more interesting after that. Stipe's lyrics are unusually direct here."
    },
    {
        id: "angstlos",
        title: "Angstlos",
        artist: "Nina Hagen",
        year: "1983",
        theme: "light",
        sky: "images/angstlos_sky.jpg",
        temp: 10,
        tempPosition: 30,
        visibility: "Moderate",
        pressure: "Erratic",
        skyDesc: "Electric, Storm-Edged",
        desc: "Nina Hagen doing whatever she wants, which is the only mode she has. Opera trained, punk aligned, new wave adjacent. Her voice is genuinely unlike anything else."
    },
    {
        id: "hallowed-ground",
        title: "Hallowed Ground",
        artist: "Violent Femmes",
        year: "1984",
        theme: "light",
        sky: "images/hallowed-ground_sky.jpg",
        temp: 11,
        tempPosition: 33,
        visibility: "Moderate",
        pressure: "Low, Dry",
        skyDesc: "Prairie Dusk, Amber Tinge",
        desc: "Darker and more country-inflected than the debut. Jesus and death and the American plains. Country Death Song is devastating and they play it like a campfire story."
    },
    {
        id: "war",
        title: "War",
        artist: "U2",
        year: "1983",
        theme: "light",
        sky: "images/war_sky.jpg",
        temp: 12,
        tempPosition: 35,
        visibility: "Moderate",
        pressure: "Building",
        skyDesc: "Cold Sun, Broken Cloud",
        desc: "The Edge's guitar work on Sunday Bloody Sunday is the whole argument for this record. U2 at their most urgent, before the stadium ambition took over completely."
    },
    {
        id: "snap",
        title: "Snap!",
        artist: "The Jam",
        year: "1983",
        theme: "light",
        sky: "images/snap_sky.jpg",
        temp: 12,
        tempPosition: 37,
        visibility: "Good",
        pressure: "Steady",
        skyDesc: "Bright, Brittle Blue",
        desc: "Double compilation covering the full run. Weller's songwriting gets better with almost every single. Town Called Malice, Going Underground, The Eton Rifles — the run of great songs is hard to argue with."
    },
    {
        id: "gravity-talks",
        title: "Gravity Talks",
        artist: "Green on Red",
        year: "1983",
        theme: "light",
        sky: "images/gravity-talks_sky.jpg",
        temp: 13,
        tempPosition: 39,
        visibility: "Good",
        pressure: "Steady, Dry",
        skyDesc: "Desert Pale, Washed Out",
        desc: "Paisley underground at its most druggy and loose. Organs, jangle, and a hazy Velvet Underground influence. The kind of record that sounds best in the afternoon."
    },
    {
        id: "franks-wild-years",
        title: "Frank's Wild Years",
        artist: "Tom Waits",
        year: "1987",
        theme: "light",
        sky: "images/franks-wild-years_sky.jpg",
        temp: 13,
        tempPosition: 41,
        visibility: "Low",
        pressure: "Falling, Damp",
        skyDesc: "Neon-Stained, Wet Night",
        desc: "Theatrical, carnival-dark, and genuinely funny in places. Waits doing the character work from Swordfishtrombones but pushed further into the absurd. Hang On St. Christopher is one of his best."
    },
    {
        id: "more-songs",
        title: "More Songs About Buildings and Food",
        artist: "Talking Heads",
        year: "1978",
        theme: "light",
        sky: "images/more-songs_sky.jpg",
        temp: 14,
        tempPosition: 43,
        visibility: "Good",
        pressure: "Steady",
        skyDesc: "Flat White, Suburban Noon",
        desc: "Brian Eno's production loosens the debut's tension just enough. Take Me to the River is the obvious entry point but the whole record has a nervous, functional energy that's hard to shake."
    },
    {
        id: "green-on-red",
        title: "Green on Red",
        artist: "Green on Red",
        year: "1982",
        theme: "light",
        sky: "images/green-on-red_sky.jpg",
        temp: 14,
        tempPosition: 45,
        visibility: "Moderate",
        pressure: "Steady, Warm Edge",
        skyDesc: "Dusty, Late Afternoon",
        desc: "Early EP, rawer than Gravity Talks. The template is already there though — organ-heavy, slightly unfocused, more interested in mood than structure. Worth having."
    },
    {
        id: "golden-shower",
        title: "Golden Shower of Hits",
        artist: "Circle Jerks",
        year: "1983",
        theme: "light",
        sky: "images/golden-shower_sky.jpg",
        temp: 15,
        tempPosition: 47,
        visibility: "Good",
        pressure: "High, Restless",
        skyDesc: "Glaring, Bleached White",
        desc: "Covers record that works better than it should. They run through Redd Kross, Gary Numan, and Afternoon Delight in the same breathless set. Irreverent and fast."
    },
    {
        id: "dance-pieces",
        title: "Dance Pieces",
        artist: "Philip Glass",
        year: "1987",
        theme: "light",
        sky: "images/dance-pieces_sky.jpg",
        temp: 15,
        tempPosition: 49,
        visibility: "Excellent",
        pressure: "High, Still",
        skyDesc: "Pale, Motionless Blue",
        desc: "Three pieces written for dance. In the Upper Room in particular has a drive that most of Glass's work doesn't. Repetitive in the way that becomes hypnotic rather than tedious."
    },
    {
        id: "washington-square",
        title: "Washington Square",
        artist: "Washington Square Stompers",
        year: "1963",
        theme: "dark",
        sky: "images/washington-square_sky.jpg",
        temp: 16,
        tempPosition: 51,
        visibility: "Good",
        pressure: "Steady, Mild",
        skyDesc: "Soft, Hazy Afternoon",
        desc: "Folk revival record from the Village scene. Jug band and old-timey string arrangements. Cheerful and unpretentious in a way that a lot of the revival stuff wasn't."
    },
    {
        id: "on-film",
        title: "On Film",
        artist: "Cab Calloway",
        year: "1982",
        theme: "dark",
        sky: "images/on-film_sky.jpg",
        temp: 17,
        tempPosition: 53,
        visibility: "Good",
        pressure: "Steady, Warm",
        skyDesc: "Smoky, Spotlight Gold",
        desc: "Soundtrack recordings compiled from his film appearances. Minnie the Moocher in particular — recorded for the screen, which means the performance is pitched to the back row. Hi-de-ho."
    },
    {
        id: "bandana",
        title: "Bandana",
        artist: "Freddie Gibbs",
        year: "2019",
        theme: "light",
        sky: "images/bandana_sky.jpg",
        temp: 17,
        tempPosition: 55,
        visibility: "Moderate",
        pressure: "Warm, Hazy",
        skyDesc: "Amber Dusk, Smoked",
        desc: "Second Gibbs and Madlib collaboration. Tighter and more focused than Piñata. Gibbs raps like he has nothing to prove, which is its own kind of confidence."
    },
    {
        id: "man-and-woman",
        title: "A Man and a Woman",
        artist: "Francis Lai",
        year: "1966",
        theme: "dark",
        sky: "images/man-and-woman_sky.jpg",
        temp: 18,
        tempPosition: 57,
        visibility: "Good",
        pressure: "Gentle, Rising",
        skyDesc: "Soft Grey, Silver-Edged",
        desc: "Film score, but the main theme is one of those melodies that burrows in and stays. Lai builds around it with small variations. Romantic without being saccharine."
    },
    {
        id: "for-love-of-ivy",
        title: "For Love of Ivy",
        artist: "Quincy Jones",
        year: "1968",
        theme: "dark",
        sky: "images/for-love-of-ivy_sky.jpg",
        temp: 19,
        tempPosition: 59,
        visibility: "Good",
        pressure: "Settled, Warm",
        skyDesc: "Lazy, Blue-Gold Blend",
        desc: "Quincy scoring a Sidney Poitier film. The title theme with BB King vocal is the obvious highlight. The rest of the record is good background-becoming-foreground music."
    },
    {
        id: "so",
        title: "So",
        artist: "Peter Gabriel",
        year: "1986",
        theme: "dark",
        sky: "images/so_sky.jpg",
        temp: 19,
        tempPosition: 61,
        visibility: "Good",
        pressure: "Steady, Building Warmth",
        skyDesc: "Wide, Open Blue",
        desc: "Sledgehammer is the hit but Mercy Street is the reason. Gabriel's production is dense and considered. The record holds together as a full listen better than most 80s pop."
    },
    {
        id: "in-the-crowd",
        title: "In the Crowd",
        artist: "Ramsey Lewis Trio",
        year: "1965",
        theme: "dark",
        sky: "images/in-the-crowd_sky.jpg",
        temp: 20,
        tempPosition: 63,
        visibility: "Good",
        pressure: "Steady, Warm",
        skyDesc: "Bright, Crowded Blue",
        desc: "Live jazz record with a real audience energy. The crowd responses are part of the performance. Lewis plays with a looseness that the studio recordings don't always have."
    },
    {
        id: "chu",
        title: "Chu",
        artist: "Chu Berry & His Stompy Stevedores",
        year: "1937",
        theme: "dark",
        sky: "images/chu_sky.jpg",
        temp: 22,
        tempPosition: 65,
        visibility: "Good",
        pressure: "Steady, Settled",
        skyDesc: "Warm, Golden Edged",
        desc: "Swing era tenor sax, pre-war and full of momentum. Berry died young and didn't leave much behind. What's here is warm, generous playing — the kind that makes a room feel larger."
    },
    {
        id: "jacquet-street",
        title: "Jacquet Street",
        artist: "Illinois Jacquet",
        year: "1987",
        theme: "dark",
        sky: "images/jacquet-street_sky.jpg",
        temp: 22,
        tempPosition: 67,
        visibility: "Good",
        pressure: "Warm, Settled",
        skyDesc: "Honeyed, Late Sun",
        desc: "Late career record on Verve, unhurried and confident. Jacquet had been playing since the 40s by this point and it shows — everything is exactly where it needs to be."
    },
    {
        id: "seven-year-ache",
        title: "Seven Year Ache",
        artist: "Rosanne Cash",
        year: "1981",
        theme: "dark",
        sky: "images/seven-year-ache_sky.jpg",
        temp: 23,
        tempPosition: 70,
        visibility: "Good",
        pressure: "Warm, Steady",
        skyDesc: "Wide Prairie, Fading Gold",
        desc: "Country that crosses into pop without losing its grounding. The title track is one of those songs that sounds like it already existed before she wrote it. Rodney Crowell production throughout."
    },
    {
        id: "hes-the-king",
        title: "He's the King",
        artist: "Al Hirt",
        year: "1963",
        theme: "dark",
        sky: "images/hes-the-king_sky.jpg",
        temp: 24,
        tempPosition: 72,
        visibility: "Excellent",
        pressure: "High, Warm",
        skyDesc: "Bright Bayou, Deep Blue",
        desc: "New Orleans trumpet, big and brassy. Hirt had a tone you could pick out of any room. Dixieland energy with a pop sensibility. The kind of record that was background music and deserves better."
    },
    {
        id: "journey-to-love",
        title: "Journey to Love",
        artist: "Stanley Clarke",
        year: "1975",
        theme: "dark",
        sky: "images/journey-to-love_sky.jpg",
        temp: 24,
        tempPosition: 74,
        visibility: "Excellent",
        pressure: "Warm, Rising",
        skyDesc: "Rich, Saturated Blue",
        desc: "Jazz fusion with a bass player as the center of gravity. Jeff Beck guests and it works. Clarke plays both acoustic and electric and moves between them like they're the same instrument."
    },
    {
        id: "legendary-performer",
        title: "A Legendary Performer",
        artist: "Henry Mancini",
        year: "1976",
        theme: "dark",
        sky: "images/legendary-performer_sky.jpg",
        temp: 25,
        tempPosition: 76,
        visibility: "Excellent",
        pressure: "High, Settled",
        skyDesc: "Warm, Cinematic Gold",
        desc: "Compilation of Mancini's best known themes. Moon River, Pink Panther, Days of Wine and Roses. The arrangements are impeccable. His orchestrations are the reason these melodies endure."
    },
    {
        id: "boogie-woogie",
        title: "The Original Boogie Woogie Piano Giants",
        artist: "Various",
        year: "1977",
        theme: "dark",
        sky: "images/boogie-woogie_sky.jpg",
        temp: 26,
        tempPosition: 79,
        visibility: "Good",
        pressure: "High, Warm",
        skyDesc: "Hazy, Bourbon-Gold",
        desc: "Meade Lux Lewis, Albert Ammons, Pete Johnson — the three pianists who defined the style. Recordings from the late 30s and early 40s. The left hand work alone is worth the price."
    },
    {
        id: "beat-of-big-bands",
        title: "The Beat of the Big Bands",
        artist: "Artie Shaw",
        year: "1967",
        theme: "dark",
        sky: "images/beat-of-big-bands_sky.jpg",
        temp: 26,
        tempPosition: 81,
        visibility: "Excellent",
        pressure: "High, Warm, Settled",
        skyDesc: "Ballroom Gold, Still Air",
        desc: "Shaw re-recording his hits in stereo. Begin the Beguine is the centerpiece. The newer versions are crisper but the spirit is intact. Shaw quit music young and spent the rest of his life explaining why."
    },
    {
        id: "song-for-you",
        title: "A Song for You",
        artist: "Carpenters",
        year: "1972",
        theme: "dark",
        sky: "images/song-for-you_sky.jpg",
        temp: 27,
        tempPosition: 83,
        visibility: "Excellent",
        pressure: "High, Gentle",
        skyDesc: "Soft, Warm Peach",
        desc: "Karen Carpenter's voice is the whole argument. Superstar and Hurting Each Other back to back is an emotional sequence that doesn't announce itself. Impeccably produced without being cold."
    },
    {
        id: "you-better-move-on",
        title: "You Better Move On",
        artist: "The Rolling Stones",
        year: "1964",
        theme: "dark",
        sky: "images/you-better-move-on_sky.jpg",
        temp: 29,
        tempPosition: 90,
        visibility: "Excellent",
        pressure: "High, Building Heat",
        skyDesc: "Restless, Hot White Sky",
        desc: "Early EP from the first UK period. Blues covers, rough around the edges, and better for it. You can hear them figuring out what they want to be. The title track is the one."
    },
    {
        id: "20-explosive-hits",
        title: "20 Explosive Hits",
        artist: "20 Original Stars",
        year: "1979",
        theme: "dark",
        sky: "images/20-explosive-hits_sky.jpg",
        temp: 32,
        tempPosition: 97,
        visibility: "Hazy",
        pressure: "High, Oppressive",
        skyDesc: "Bleached, Shimmering Heat",
        desc: "K-Tel style compilation from the late 70s. Half the tracks are ones you know, half are ones you don't, and the ones you don't are often the better half. The format is honest about what it is."
    }
];